### PR TITLE
Some Changes to lay a foundation

### PR DESCRIPTION
**Pull request by simonwoegerb**
Yes, I know I changed quite a lot in comparison to your base layout and I am sorry for that! But in my opinion this just makes more sense. 

My CommandHandler is taken from one of my plugins ([EssentialsReloaded](https://gitlab.com/auster/EssentialsReloaded)) and works very well there. It looks like mad magic but it really is not. 
If you want I can add some of the other things i built there to this core plugin too.

### CODE REVIEW

**Comment by drpheonixgaming2288** [comment]
Thanks so much! I will use this. If you don't mind of course!

**Comment by simonwoegerb** [comment]
I wouldn't have made a PR if i didn't allow you to use it, would i? Gonna add some other stuff tomorrow too, like config handling and such.

Btw got any plan on what kind of core plugin you wanna make? Library or standalone core?

**Comment by drpheonixgaming2288** [comment]
Tysm. I just want to make a plugin that can do most things like /vanish, /mail, etc.

**Comment by simonwoegerb** [comment]
So basically Essentials without the bloat?
If so I could like literally add all of EssentialsReloaded here too lmao

**Comment by drpheonixgaming2288** [comment]
Yeah basically. Maybe more better/more useful features.

**Comment by simonwoegerb** [comment]
I see. I am gonna add basically all of EssR here (it's not that much tbh) if you dont mind tomorrow

**Comment by drpheonixgaming2288** [comment]
Okay. Yeah sure go for it. Thanks.

**Comment by simonwoegerb** [comment]
By the way, would you mind giving me commit access so i don't Always have to wait for you to approve my PR? 
You don't have to of course, it'd just be more convenient!

**Comment by drpheonixgaming2288** [comment]
Sure!

**Comment by simonwoegerb** [comment]
Lovely, Thanks!

**Comment by drpheonixgaming2288** [comment]
Hold up I can't figure it out hah.

**Comment by drpheonixgaming2288** [comment]
Okay your invited

**Comment by simonwoegerb** [comment]
Finally found the invitation thanks :)
Really gotta go catch some sleep now, its like 1pm around here haha

**Pull request merged**
